#   
#### DOCUMENTATION OF CONFIG FILE FOR NETWORK WRAPPER ####
#
#For the current development, we use a single (default) config profile per file
# It is divided into four sections :
#  1. Input Profile
#  2. Provenanace
#  3. Output Profile
#  4. Computing Specs
# Each of these sections are further divided into subsections and tags that has to be added and required for most cases, else filled as NULL
#
#
default:
  input_profile:
    input_synid:  syn000000 # The Synapse ID of the input file is to provided; User has to make sure that their synapse profile has access to this particular profile
    project_id:  syn000001 # The Synapse ID of the Project folder currently the user owns to build provenance and upload files 
    network_method: ["c3net"] # The type of network methods to be used in a list format with quotes. 
    # The options in light network include c3net, mrnet, wgcna;
    # The options in light network include lassoAIC, lassoBIC, lassoCV1se, lassoCVmin, ridgeAIC, ridgeBIC, ridgeCV1se, ridgeCVmin, sparrowZ, sparrow2Z;
    # The options in light network include genie3 and tigress;
    p_val_c3net: 1 # P - value threshold for the C3Net method, if specified in network_method, else leave blank or NULL
    p_val_mrnet: 1 # P - value threshold for the mrnet method, if specified in network_method, else leave blank or NULL
    p_val_wgcna: 1 # P - value threshold for the WGCNA method, if specified in network_method, else leave blank or NULL
    temp_storage_loc: /home/sage # Temporary file storage location for the input file which will be deleted after completion of the process
    rsquaredCut: 0.80 # R squared cutt-off for the WGCNA network method and if not used, leave blank or NULL
    defaultnaPower: 6 # Default NA power value for WGCNA network method and if not used, leave blank or NULL
  provenance:
    annotations: # Provenance annoation subsections - can be obtained from the parent syn ID
      data_type: ['clinical','geneExpression'] #
      resource_type: metadata
      metadata_type: 'analytical covariates'
      ismodelsystem: FALSE
      ismultispecimen: TRUE
      fileformat: csv
      grant: U01AG046152
      species: Human
      organ: brain
      tissue: ['dorsolateral prefrontal cortex', 'Head of caudate nucleus', 'posterior cingulate cortex']
      study: ["ROSMAP","rnaSeqReprocessing"]
      consortium: AMP-AD
      assay: rnaSeq
    code_annotations: # For development purpose only # Do not change the code annotations unless user determines to use another analysis pipeline
        repository: PradoVarathan/Reprocessing_Metanetwork_Analysis # The current repository from where the analysis code is obtained from - DO NOT CHANGE
        ref: branch 
        ref_name: main
        repository_path: Network_Wrapper.R # The code block path in the repository used for analysis
    activity_name: c3net_rosmap_network # The activity name for Synapase Provenance path creation
    activity_description: 'Using the c3net to prepare network from rosmap data' # Detailed explanation of the activity in quotes to be updated on Synapse
  output_profile:
    output_path: Rosmap_c3net # The full path for the final output file
    output_name: 'Final Rosmap Network from C3Net' # The output name as to be updated in Synapse Project
    error_path: Rosmap_c3net_error # The full path for the error file from the process
  computing_specs:
  # Total number of cores available for the process and if not being used, leave blank or NULL 
    light_ncores: 96    
    medium_ncores: 
    heavy_ncores: 