default:
  input_profile:
    input_folderid: syn25953317
    project_id: syn25953317
    input_proj_id: syn21266454
    temp_storage_loc: /home/sage
    temp_input_loc: /home
    pattern_id: Network
  provenance:
    annotations:
      data_type: ['clinical','geneExpression']
      resource_type: metadata
      metadata_type: 'analytical covariates'
      ismodelsystem: FALSE
      ismultispecimen: TRUE
      fileformat: csv
      grant: U01AG046152
      species: Human
      organ: brain
      tissue: ['dorsolateral prefrontal cortex', 'Head of caudate nucleus', 'posterior cingulate cortex']
      study: ["ROSMAP","rnaSeqReprocessing"]
      consortium: AMP-AD
      assay: rnaSeq
    code_annotations:
        repository: PradoVarathan/Reprocessing_Metanetwork_Analysis
        ref: branch
        ref_name: main
        repository_path: Consensus_Wrapper.R
    activity_name: ConsensusBuild_syn21266454
    activity_description: 'Using the networks to prepare a consensus network from syn21266454 data'
  output_profile:
    output_path: syn21266454
    md5_output_path: syn21266454md5.out
    output_name: 'syn21266454 Consensus Network '
    error_path: syn21266454_consensus_err
