default:
  input_profile:
    input_synid: syn25874033
    project_id: syn25872026
    network_method: ["c3net","mrnet","wgcna"]
    na_fill: NULL
    p_val_c3net: 1
    p_val_mrnet: 1
    p_val_wgcna: 1
    temp_storage_loc: /home/sage
    rsquaredCut: 0.80
    defaultnaPower: 6
  provenance:
    annotations:
      data_type: ['clinical','geneExpression']
      resource_type: metadata
      metadata_type: 'analytical covariates'
      ismodelsystem: FALSE
      ismultispecimen: TRUE
      fileformat: csv
      grant: U01AG046152
      species: Human
      organ: brain
      tissue: ['dorsolateral prefrontal cortex', 'Head of caudate nucleus', 'posterior cingulate cortex']
      study: ["ROSMAP","rnaSeqReprocessing"]
      consortium: AMP-AD
      assay: rnaSeq
    code_annotations:
        repository: PradoVarathan/Reprocessing_Metanetwork_Analysis
        ref: branch
        ref_name: main
        repository_path: Test_Scripts/Light_Networks.R
    activity_name: LightNet_Test
    activity_description: 'Testing light networks with sample simulated data'
  output_profile:
    output_path: /home/sage
    md5_output_path: Simulation_md5.out
    output_name: 'Networks from Simulation data'
    error_path: simulation_error_light
  computing_specs:
    light_ncores: 96
    medium_ncores: 32
    heavy_ncores: 256